stages:
  - install
  - build
  - test
  - quality

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules

install:
  stage: install
  image: node:14.15.1
  script:
    - yarn install

build:
  stage: build
  image: node:14.15.1
  script:
    - yarn build-storybook
    - yarn build && yarn export
  artifacts:
    paths:
      - storybook-static/
      - out/

test:
  stage: test
  image: buildkite/puppeteer:5.2.1
  script:
    - yarn test-all
  dependencies:
    - build
  artifacts:
    paths:
      - coverage/

sonar-scanner:
  stage: quality
  image: node:14.15.1
  script:
    - yarn sonar-scanner
  dependencies:
    - test
  only:
    - develop
  allow_failure: true

# deploy:
#   stage: deploy
#   image: node:14.15.1
#   before_script:
#     - npm -g install cloudron-surfer
#   script:
#     - surfer put --token apibfd571813aac9cb164ff44da93d906ab --server infinity-doctors-web.apegro.com storybook-static/* /storybook
#     - surfer put --token apibfd571813aac9cb164ff44da93d906ab --server infinity-doctors-web.apegro.com out/* /
#   dependencies:
#     - build

# audit:
#   stage: quality
#   image: node:14.15.1
#   script:
#     - yarn audit
#   allow_failure: true
